# Generated by Django 3.1.4 on 2021-03-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstOne', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='location',
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='average_earning',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='clothes_expenses',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='creams_expenses',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='height',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='makeup_expenses',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
