# Generated by Django 3.1.4 on 2021-03-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstOne', '0002_auto_20210325_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
