# Generated by Django 3.1.4 on 2021-03-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstOne', '0003_person_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='note',
        ),
    ]
