# Generated by Django 3.1.4 on 2021-03-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstOne', '0004_remove_person_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
