# Generated by Django 3.1.7 on 2021-03-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstOne', '0005_person_note'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='firstone_person',
        ),
    ]
